# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [1]:
# Completar o exercício aqui
#Importando o numpy e atribuindo o alias

import numpy as np
#Criando o array
array = np.arange(10,100)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [2]:
#Invertendo o array:
print(array[::-1])

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
#Criando array 3x3
big_array = np.array([[0,1,8],[2,7,4]])
print(big_array)

[[0 1 2]
 [2 7 4]
 [5 4 2]]


In [6]:
#Criando a matriz identidade
mtr_ident = np.eye(6)
print(mtr_ident)

In [9]:
#Criando o array 3x3x3
aray_3_x_3_x_3 = np.array([[2,3,5],[3,7,5],[9,4,6]])
print(aray_3_x_3_x_3)

[[2 3 5]
 [3 7 5]
 [9 4 6]]


In [13]:
#Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais
array1 = np.array([1,6,7,2,3])
array2 = np.array([1,5,7,2,3])

results = np.equal(array1, array2)
results= (array1 == array2)
print(results)

[ True False  True  True  True]


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [17]:
# Completar o exercício aqui
#Criando o array random
dolars = np.random.randint(1,1000,100)
print(dolars)

[897 806 306 987 629 724 146 692 663 623 557 106 987 683 352 608 102 575
 974 253 604 846 781 460 227   8 722 287 868 399 581 527 218 952 221  63
 370 653  68 672 703 557 805 556 579 975 270 112 850 512 629 701 521 973
 401 708 916 597 257 432 305 874  88 472 182  57 973 765 355 393 875 877
 278 871  48 962 327 896 460 382 253 135 859 263 423 553 200 676 755 134
 386 955 287 649 576 609 955 129 574 380]


In [25]:
#Convertendo
exchange = 0.874413
euro = dolars * exchange
around = np.round(euro, 2)
print("A nossa conversão fica:\n\n", around)

A nossa conversão fica:

 [784.35 704.78 267.57 863.05 550.01 633.08 127.66 605.09 579.74 544.76
 487.05  92.69 863.05 597.22 307.79 531.64  89.19 502.79 851.68 221.23
 528.15 739.75 682.92 402.23 198.49   7.   631.33 250.96 758.99 348.89
 508.03 460.82 190.62 832.44 193.25  55.09 323.53 570.99  59.46 587.61
 614.71 487.05 703.9  486.17 506.29 852.55 236.09  97.93 743.25 447.7
 550.01 612.96 455.57 850.8  350.64 619.08 800.96 522.02 224.72 377.75
 266.7  764.24  76.95 412.72 159.14  49.84 850.8  668.93 310.42 343.64
 765.11 766.86 243.09 761.61  41.97 841.19 285.93 783.47 402.23 334.03
 221.23 118.05 751.12 229.97 369.88 483.55 174.88 591.1  660.18 117.17
 337.52 835.06 250.96 567.49 503.66 532.52 835.06 112.8  501.91 332.28]


**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [2]:
# Completar o exercício aqui
import pandas as pd


#Abrindo e mostrando o csv Titulos
df1 = pd.read_csv("05_05_imdb_titulos.csv")
df1.head()

title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

In [41]:
#Mostrando quantos titulos há:
print(f"O número de registros corresponde a: {len(df1)}")

O número de registros corresponde a: 3564650


In [ ]:
#Os 5 mais antigos
df1['year'] = pd.to_datetime(df1['year'], format='%Y')

In [47]:
df_ordem = df1.sort_values(by='year')
top_5_antigos = df_ordem.head(5)
print("Os filmes mais antigos são:\n\n",top_5_antigos)

Os filmes mais antigos são:

                          title  year               name     type  \
548900              Miss Jerry  1894     Chauncey Depew    actor   
458905              Miss Jerry  1894  William Courtenay    actor   
2482629             Miss Jerry  1894    Blanche Bayliss  actress   
1696551  Soldiers of the Cross  1900        Orrie Perry    actor   
1696702  Soldiers of the Cross  1900          Reg Perry    actor   

                                                 character   n  
548900   Himself - the Director of the New York Central... NaN  
458905                                        Mr. Hamilton NaN  
2482629               Miss Geraldine Holbrook (Miss Jerry) NaN  
1696551                                               Lion NaN  
1696702                                               Lion NaN  


In [7]:
# Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
filmes_dracula = df1[df1['title'].str.contains('Dracula', case=False)]
print('Existem', len(filmes_dracula), "Filmes drácula", "são eles: \n", filmes_dracula)

Existem 84 Filmes drácula são eles: 
                                   title  year
3903         Bonnie & Clyde vs. Dracula  2008
4851                   House of Dracula  1945
13441                    Batman Dracula  1964
15371   Young-guwa heubhyeolgwi dracula  1992
20794                 Terror of Dracula  2012
...                                 ...   ...
214826                    Dracula's Dog  1978
221137                      Dracula Now  2015
224233     The Satanic Rites of Dracula  1973
228121                   Son of Dracula  1974
229161               Dracula and Stoker  2012

[84 rows x 2 columns]


In [10]:
#Mostrar os 10 títulos mais comuns (que mais se repetem)
contagem = df1['title'].value_counts()
print(f"Os que mais se repetem são: \n{contagem.head(10)}")

Os que mais se repetem são: 
Hamlet                  19
Carmen                  16
Macbeth                 15
Maya                    11
The Outsider            11
Hero                    11
Othello                 11
The Three Musketeers    11
Anna                    10
Vengeance               10
Name: title, dtype: int64


In [12]:
#Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
# Confesso que essa ultima funçõ iloc, foi mais chato de achar.

first_romeo = df1.loc[df1['title'] == 'Romeo and Juliet'].iloc[0]

print("O primeiro romeu foi: ", first_romeo)

O primeiro romeu foi:  title    Romeo and Juliet
year                 2014
Name: 16975, dtype: object


In [14]:
# Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
filmes_exc = df1[df1['title'].str.contains('Exorcist', case=False)]
ordem_filmes = filmes_exc.sort_values(by='year')
print(ordem_filmes)

                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
51101                            Bad Exorcists  2015
151850                              Exorcistas  2015
60700                      Accidental Exorcist  2016
161093                       American Exorcist

In [29]:
# Mostrar quantos filmes foram feitas no ano 1950
filme = df1[df1['year'] == 1950]
df1.columns
total_filmes = filme

print(f"Foram {len(total_filmes)} filmes feitos em 1950")

Foram 1081 filmes feitos em 1950


In [4]:
# Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
filme = df1[df1['year'].between(1950, 1959)]
contagem_filmes = len(filme)
print(f"Foram produzidor entre 1950 e 1959, {contagem_filmes}")

Foram produzidor entre 1950 e 1959, 12606


In [20]:
#Abrindo e mostrando o CSV elenco
df2 = pd.read_csv("05_05_imdb_elenco.csv")
df2.head()

title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

In [42]:
#Mostrando quantos titulos há:
print(f"O número de registros corresponde a: {len(df2)}")

O número de registros corresponde a: 3564650


In [6]:
# Mostrar todas os papéis que teve a trilogia “The Godfather”, 
# agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu 
# (exemplo: michael corleone aparece nos 3 filmes da triologia).

godfather_trilogy = df2[df2['title'].str.contains('The Godfather', case=False)]
papeis_contagem = godfather_trilogy['character'].value_counts()
print(papeis_contagem)

Extra                     5
Sandra Corleone           2
Street Vendor             2
Lucy Mancini              2
Al Neri                   2
                         ..
Anthony, the Bodyguard    1
Don Zaluchi               1
Douglas Michelson         1
B.J. Harrison             1
Governess                 1
Name: character, Length: 262, dtype: int64


In [16]:
# Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
dracula_1958 = df2[(df2['title'] == 'Drácula') & (df2['year'] == 1958)]
elenco_dracula_1958 = dracula_1958.sort_values(by='n')
print(dracula_1958)

Empty DataFrame
Columns: [title, year, name, type, character, n]
Index: []


In [11]:
# Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
# Mostrar quantos papéis fez “Robert de Niro” na sua carreira.


papeis_bruce_wayne = df2[(df2['name'].str.contains('Bruce Wayne', case=False, na=False)) & (df2['n'] == 1)].shape[0]

papeis_robert_de_niro = df2[df2['name'] == 'Robert de Niro'].shape[0]

# Imprimir os resultados
print("Bruce Wayne como protagonista:", papeis_bruce_wayne)
print("Papéis de Robert de Niro:", papeis_robert_de_niro)

Bruce Wayne como protagonista: 0
Papéis de Robert de Niro: 0


In [21]:
#Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado por ano de forma descendente.
# Filtrar os registros onde "Charlton Heston" é protagonista (n=1) e na década de 60
papeis_charlton_heston_60s = df2[(df2['name'] == 'Charlton Heston') & (df2['n'] == 1) & (df2['year'] >= 1960) & (df2['year'] <= 1969)]

# Ordenar por ano de forma descendente
papeis_charlton_heston_60s_ordenados = papeis_charlton_heston_60s.sort_values(by='year', ascending=False)

# Imprimir o resultado
print(papeis_charlton_heston_60s_ordenados)

                            title  year             name   type  \
944074                 Number One  1969  Charlton Heston  actor   
944077         Planet of the Apes  1968  Charlton Heston  actor   
944050               Counterpoint  1967  Charlton Heston  actor   
944120                 Will Penny  1967  Charlton Heston  actor   
944066                   Khartoum  1966  Charlton Heston  actor   
944068               Major Dundee  1965  Charlton Heston  actor   
944085  The Agony and the Ecstasy  1965  Charlton Heston  actor   
944111               The War Lord  1965  Charlton Heston  actor   
944038          55 Days at Peking  1963  Charlton Heston  actor   
944052               Diamond Head  1962  Charlton Heston  actor   
944101  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944102  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944103  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944054                     El Cid  1961  Charlton Heston  acto

In [19]:
#Mostrar quantos papéis para atores teve na década 50’s.
papeis_decada_50 = df[df['year'].between(1950, 1959)]
total_papeis_decada_50 = papeis_decada_50.shape[0]
print("Total de papéis para atores na década de 50:", total_papeis_decada_50)

Total de papéis para atores na década de 50: 210002


In [22]:
#Mostrar quantos papéis para atrizes teve na década 50’s.
papeis_atrizes_decada_50 = df2[(df2['year'].between(1950, 1959)) & (df2['type'] == 'actress')]
total_papeis_atrizes_decada_50 = papeis_atrizes_decada_50.shape[0]
print("Total de papéis para atrizes na década de 50:", total_papeis_atrizes_decada_50)

Total de papéis para atrizes na década de 50: 56004
